Feature/tx sync improvement
zvchain/zvchain pull request #411
Opened 2019-10-24 08:22 UTC by bird512

2019-10-24 15:08 UTC, darren0718 requested changes

2019-10-24 15:08 UTC, darren0718 commented on core/tx_sync.go
> +			if strings.Contains(err.Error(), "nonce error") {
bad check, should use constant error instead

2019-10-24 15:08 UTC, darren0718 commented on core/tx_sync.go
> +		nonceErrTxs:   common.MustNewLRUCache(3000),
this cache size can be larger, say 20000

2019-10-25 06:07 UTC, bird512 commented on core/tx_sync.go
> +		nonceErrTxs:   common.MustNewLRUCache(3000),
3000 should be git enough. because it will not have so many nonce error transactions amount the network if every body upgraded client.

2019-10-25 06:24 UTC, sesamegu commented on core/simple_container.go
> +			c.clearRoute()
add time monitor

2019-10-25 06:29 UTC, sesamegu commented on core/tx_sync.go
> +			}
add return

2019-10-25 06:52 UTC, bird512 commented on core/simple_container.go
> +			c.clearRoute()
added

2019-10-25 06:54 UTC, bird512 commented on core/tx_sync.go
> +			}
continued

2019-10-28 04:30 UTC, darren0718 approved these changes

2019-10-28 05:49 UTC, liuhaox1 approved these changes

2019-10-28 05:58 UTC, merged