Features/black
zvchain/zvchain pull request #68
Opened 2019-07-01 05:01 UTC by liuhaox1

2019-07-01 06:05 UTC, bird512 commented on core/peers_meter.go
> +	m.timeoutMeter = 0
function name deceaseTime mismatch what it does inside (m.timeoutMeter = 0)

2019-07-01 07:42 UTC, darren0718 requested changes

2019-07-01 07:42 UTC, darren0718 commented on core/peers_meter.go
peerMeter needs unit test

2019-07-01 07:42 UTC, darren0718 commented on core/transaction_pool.go
> +		if _,ok:=evilErrorMap[err];ok{
Is error addressable? what about err == nil ?

2019-07-01 07:42 UTC, darren0718 commented on core/tx_sync.go
> +	}
why count > txMaxReceiveLimit ? should be txMaxNotifyPerTime

2019-07-01 07:42 UTC, darren0718 commented on core/tx_sync.go
> +	if len(txs) > txReceiveMaxLimit{
should be txMaxNotifyPerTime.
txReceiveMaxLimit(1000) too much!!!

2019-07-02 07:28 UTC, darren0718 submitted a review, later dismissed

2019-07-08 06:30 UTC, sesamegu approved these changes
ok

2019-07-08 06:30 UTC, sesamegu commented on core/block_sync.go
> +	if candidateID == ""{
why should candidateID must be null?

2019-07-08 06:30 UTC, sesamegu commented on core/peers_meter.go
> +	maxEvilExpireTime = "1m"
maxEvilExpireTime is not a good name

2019-07-08 06:30 UTC, sesamegu commented on core/transaction_pool.go
> +var evilErrorMap map[error]struct{} = map[error]struct{}{
type can be omitted

2019-07-08 06:30 UTC, sesamegu commented on core/tx_sync.go
> +func (ptk *peerTxsHashs) checkReceivedHashsInHitRate(txs []*types.Transaction)bool {
add unit test

2019-07-09 06:59 UTC, merged